// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubastaYa.Infrastructure.Persistencia;

#nullable disable

namespace SubastaYa.Infrastructure.Migrations
{
    [DbContext(typeof(SubastaYaDbContext))]
    [Migration("20260910193751_AgregarRelacionPujasYEnum")]
    partial class AgregarRelacionPujasYEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_retenido");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_total");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ux_billeteras_usuario_id");

                    b.ToTable("billeteras", null, t =>
                        {
                            t.HasCheckConstraint("ck_billeteras_saldos", "saldo_total >= 0 AND saldo_retenido >= 0 AND saldo_retenido <= saldo_total");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SaldoRetenido = 0m,
                            SaldoTotal = 0m,
                            UsuarioId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Version = 1L
                        },
                        new
                        {
                            Id = 2,
                            SaldoRetenido = 45000m,
                            SaldoTotal = 150000m,
                            UsuarioId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Version = 1L
                        },
                        new
                        {
                            Id = 3,
                            SaldoRetenido = 0m,
                            SaldoTotal = 200000m,
                            UsuarioId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Version = 1L
                        },
                        new
                        {
                            Id = 4,
                            SaldoRetenido = 0m,
                            SaldoTotal = 500m,
                            UsuarioId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("UrlIcono")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url_icono");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_nombre");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.MovimientoBilletera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("integer")
                        .HasColumnName("billetera_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("operacion_id");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("integer")
                        .HasColumnName("subasta_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("OperacionId")
                        .HasDatabaseName("ix_movimientos_operacion_id");

                    b.HasIndex("SubastaId");

                    b.HasIndex("BilleteraId", "Fecha")
                        .HasDatabaseName("ix_movimientos_billetera_fecha");

                    b.ToTable("movimientos_billetera", null, t =>
                        {
                            t.HasCheckConstraint("ck_movimientos_billetera_monto", "monto > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BilleteraId = 2,
                            Fecha = new DateTimeOffset(new DateTime(2026, 9, 8, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Monto = 150000m,
                            OperacionId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Tipo = "Deposito"
                        },
                        new
                        {
                            Id = 2L,
                            BilleteraId = 2,
                            Fecha = new DateTimeOffset(new DateTime(2026, 9, 10, 11, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Monto = 45000m,
                            OperacionId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            SubastaId = 1,
                            Tipo = "Retencion"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Puja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<Guid>("PostorId")
                        .HasColumnType("uuid")
                        .HasColumnName("postor_id");

                    b.Property<int>("SubastaId")
                        .HasColumnType("integer")
                        .HasColumnName("subasta_id");

                    b.HasKey("Id");

                    b.HasIndex("PostorId");

                    b.HasIndex("SubastaId", "Fecha")
                        .HasDatabaseName("ix_pujas_subasta_fecha");

                    b.HasIndex("SubastaId", "Monto")
                        .HasDatabaseName("ix_pujas_subasta_monto");

                    b.ToTable("pujas", null, t =>
                        {
                            t.HasCheckConstraint("ck_pujas_monto", "monto > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Fecha = new DateTimeOffset(new DateTime(2026, 9, 10, 11, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Monto = 35000m,
                            PostorId = new Guid("33333333-3333-3333-3333-333333333333"),
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 2L,
                            Fecha = new DateTimeOffset(new DateTime(2026, 9, 10, 11, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Monto = 45000m,
                            PostorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SubastaId = 1
                        },
                        new
                        {
                            Id = 3L,
                            Fecha = new DateTimeOffset(new DateTime(2026, 9, 10, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Monto = 60000m,
                            PostorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            SubastaId = 4
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<string>("DetallesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalles_json");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_entidad");

                    b.Property<Guid?>("UsuarioActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_actor_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioActorId");

                    b.HasIndex("TipoEntidad", "EntidadId", "Fecha")
                        .HasDatabaseName("ix_auditoria_entidad_fecha");

                    b.ToTable("registros_auditoria", (string)null);
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("incremento_minimo");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_base");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url_imagen");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendedor_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_subastas_estado");

                    b.HasIndex("FechaFin")
                        .HasDatabaseName("ix_subastas_fecha_fin");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VendedorId");

                    b.HasIndex("CategoriaId", "Estado")
                        .HasDatabaseName("ix_subastas_categoria_estado");

                    b.ToTable("subastas", null, t =>
                        {
                            t.HasCheckConstraint("ck_subastas_fechas", "fecha_fin > fecha_inicio");

                            t.HasCheckConstraint("ck_subastas_precios_positivos", "precio_base > 0 AND incremento_minimo > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Excelente estado, 16GB RAM",
                            Estado = "Activa",
                            FechaFin = new DateTimeOffset(new DateTime(2026, 9, 10, 12, 25, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicio = new DateTimeOffset(new DateTime(2026, 9, 10, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncrementoMinimo = 5000m,
                            PrecioBase = 30000m,
                            Titulo = "Notebook Gamer Pro",
                            UrlImagen = "https://via.placeholder.com/150",
                            VendedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Version = 1L
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descripcion = "Edición limitada año 1990",
                            Estado = "Activa",
                            FechaFin = new DateTimeOffset(new DateTime(2026, 9, 10, 12, 0, 45, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicio = new DateTimeOffset(new DateTime(2026, 9, 10, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncrementoMinimo = 2000m,
                            PrecioBase = 10000m,
                            Titulo = "Figura Coleccionable Rare",
                            UrlImagen = "https://via.placeholder.com/150",
                            VendedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Version = 1L
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 4,
                            Descripcion = "Pocos kilómetros",
                            Estado = "Programada",
                            FechaFin = new DateTimeOffset(new DateTime(2026, 9, 12, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicio = new DateTimeOffset(new DateTime(2026, 9, 11, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncrementoMinimo = 50000m,
                            PrecioBase = 1000000m,
                            Titulo = "Auto Deportivo 2020",
                            UrlImagen = "https://via.placeholder.com/150",
                            VendedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Version = 1L
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Nuevo en caja sellada",
                            Estado = "Activa",
                            FechaFin = new DateTimeOffset(new DateTime(2026, 9, 10, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicio = new DateTimeOffset(new DateTime(2026, 9, 10, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncrementoMinimo = 5000m,
                            PrecioBase = 50000m,
                            Titulo = "Smartphone Ultima Generación",
                            UrlImagen = "https://via.placeholder.com/150",
                            VendedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Version = 1L
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Descripcion = "Talle L",
                            Estado = "Activa",
                            FechaFin = new DateTimeOffset(new DateTime(2026, 9, 10, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaInicio = new DateTimeOffset(new DateTime(2026, 9, 10, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IncrementoMinimo = 2000m,
                            PrecioBase = 20000m,
                            Titulo = "Chaqueta de Cuero Vintage",
                            UrlImagen = "https://via.placeholder.com/150",
                            VendedorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Version = 1L
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Usuario Vendedor",
                            PasswordHash = "HASH_SIMULADO"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Comprador Líder",
                            PasswordHash = "HASH_SIMULADO"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Comprador Habilitado",
                            PasswordHash = "HASH_SIMULADO"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 9, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Usuario Sin Fondos",
                            PasswordHash = "HASH_SIMULADO"
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprador_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("PrecioFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_final");

                    b.Property<int>("SubastaId")
                        .HasColumnType("integer")
                        .HasColumnName("subasta_id");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId")
                        .IsUnique()
                        .HasDatabaseName("ux_ventas_subasta_id");

                    b.HasIndex("VendedorId");

                    b.ToTable("ventas", null, t =>
                        {
                            t.HasCheckConstraint("ck_ventas_precio_final", "precio_final > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Billetera", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.Domain.Entidades.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.MovimientoBilletera", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Billetera", null)
                        .WithMany()
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Subasta", null)
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Puja", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", "Postor")
                        .WithMany("Pujas")
                        .HasForeignKey("PostorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Postor");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.RegistroAuditoria", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioActorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Subasta", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany("SubastasPublicadas")
                        .HasForeignKey("UsuarioId");

                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Venta", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Subasta", null)
                        .WithOne()
                        .HasForeignKey("SubastaYa.Domain.Entidades.Venta", "SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Subasta", b =>
                {
                    b.Navigation("Pujas");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("Billetera");

                    b.Navigation("Pujas");

                    b.Navigation("SubastasPublicadas");
                });
#pragma warning restore 612, 618
        }
    }
}
