// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubastaYa.Infrastructure.Persistencia;

#nullable disable

namespace SubastaYa.Infrastructure.Migrations
{
    [DbContext(typeof(SubastaYaDbContext))]
    [Migration("20260909165957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("SaldoRetenido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_retenido");

                    b.Property<decimal>("SaldoTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_total");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid?>("UsuarioId1")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ux_billeteras_usuario_id");

                    b.HasIndex("UsuarioId1")
                        .IsUnique();

                    b.ToTable("billeteras", null, t =>
                        {
                            t.HasCheckConstraint("ck_billeteras_saldos", "saldo_total >= 0 AND saldo_retenido >= 0 AND saldo_retenido <= saldo_total");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("UrlIcono")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url_icono");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_nombre");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.MovimientoBilletera", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("integer")
                        .HasColumnName("billetera_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<Guid>("OperacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("operacion_id");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("integer")
                        .HasColumnName("subasta_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("OperacionId")
                        .HasDatabaseName("ix_movimientos_operacion_id");

                    b.HasIndex("SubastaId");

                    b.HasIndex("BilleteraId", "Fecha")
                        .HasDatabaseName("ix_movimientos_billetera_fecha");

                    b.ToTable("movimientos_billetera", null, t =>
                        {
                            t.HasCheckConstraint("ck_movimientos_billetera_monto", "monto > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Puja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<Guid>("PostorId")
                        .HasColumnType("uuid")
                        .HasColumnName("postor_id");

                    b.Property<int>("SubastaId")
                        .HasColumnType("integer")
                        .HasColumnName("subasta_id");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostorId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SubastaId", "Fecha")
                        .HasDatabaseName("ix_pujas_subasta_fecha");

                    b.HasIndex("SubastaId", "Monto")
                        .HasDatabaseName("ix_pujas_subasta_monto");

                    b.ToTable("pujas", null, t =>
                        {
                            t.HasCheckConstraint("ck_pujas_monto", "monto > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("accion");

                    b.Property<string>("DetallesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detalles_json");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_entidad");

                    b.Property<Guid?>("UsuarioActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_actor_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioActorId");

                    b.HasIndex("TipoEntidad", "EntidadId", "Fecha")
                        .HasDatabaseName("ix_auditoria_entidad_fecha");

                    b.ToTable("registros_auditoria", (string)null);
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<decimal>("IncrementoMinimo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("incremento_minimo");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_base");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url_imagen");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendedor_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_subastas_estado");

                    b.HasIndex("FechaFin")
                        .HasDatabaseName("ix_subastas_fecha_fin");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VendedorId");

                    b.HasIndex("CategoriaId", "Estado")
                        .HasDatabaseName("ix_subastas_categoria_estado");

                    b.ToTable("subastas", null, t =>
                        {
                            t.HasCheckConstraint("ck_subastas_fechas", "fecha_fin > fecha_inicio");

                            t.HasCheckConstraint("ck_subastas_precios_positivos", "precio_base > 0 AND incremento_minimo > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("comprador_id");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<decimal>("PrecioFinal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("precio_final");

                    b.Property<int>("SubastaId")
                        .HasColumnType("integer")
                        .HasColumnName("subasta_id");

                    b.Property<Guid>("VendedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendedor_id");

                    b.HasKey("Id");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId")
                        .IsUnique()
                        .HasDatabaseName("ux_ventas_subasta_id");

                    b.HasIndex("VendedorId");

                    b.ToTable("ventas", null, t =>
                        {
                            t.HasCheckConstraint("ck_ventas_precio_final", "precio_final > 0");
                        });
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Billetera", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithOne()
                        .HasForeignKey("SubastaYa.Domain.Entidades.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.Domain.Entidades.Billetera", "UsuarioId1");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.MovimientoBilletera", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Billetera", null)
                        .WithMany()
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Subasta", null)
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Puja", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("PostorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Subasta", null)
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany("Pujas")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.RegistroAuditoria", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioActorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Subasta", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany("SubastasPublicadas")
                        .HasForeignKey("UsuarioId");

                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Venta", b =>
                {
                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Subasta", null)
                        .WithOne()
                        .HasForeignKey("SubastaYa.Domain.Entidades.Venta", "SubastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.Domain.Entidades.Usuario", null)
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SubastaYa.Domain.Entidades.Usuario", b =>
                {
                    b.Navigation("Billetera");

                    b.Navigation("Pujas");

                    b.Navigation("SubastasPublicadas");
                });
#pragma warning restore 612, 618
        }
    }
}
